sudo: required

dist: trusty

language: node_js

node_js:
 - '8.7.0'

sudo: required

dist: trusty

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
- cd website
- npm install -g @angular/cli
- npm install -g karma
- npm install
- ng build

script: karma start ./website/karma.conf.js --single-run
