export { Component, OnInit, ViewChild, NgModule, Injectable } from '@angular/core';
export { MatDialog } from '@angular/material';
export { DataSource } from '@angular/cdk/collections';
export { MatPaginator } from '@angular/material';
export { BehaviorSubject } from 'rxjs/BehaviorSubject';
export { Observable } from 'rxjs/Observable';
export { HttpClientModule, HttpClient, HttpParams } from '@angular/common/http';
export { isObject } from 'util';
export { TestBed, async } from '@angular/core/testing';
export { MovieListComponent } from './movie-list/movie-list.component';
export { MovieListService } from './movie-list/movie-list.service';
export { MovieDetailsComponent } from './movie-details/movie-details.component';
export { RouterModule, Routes } from '@angular/router';
export { ProfileComponent } from './profile/profile.component';
export { HeaderComponent } from './header/header.component';
export { CdkTableModule } from '@angular/cdk/table';
export { AppComponent } from './app.component';
export { FormsModule } from '@angular/forms';
export { MatButtonModule, MatDialogModule, MatCardModule, MatIconModule, MatInputModule, MatPaginatorModule, MatSidenavModule, MatTableModule, MatToolbarModule, MatTooltipModule } from '@angular/material';
export { BrowserAnimationsModule } from '@angular/platform-browser/animations';
export { BrowserModule } from '@angular/platform-browser';
export { MovieList } from './movie-list/movie-list';
